# Generated by Django 5.1 on 2025-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcadyan_Web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedlogfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='uploadedlogfile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedlogfile',
            name='file',
            field=models.FileField(upload_to='log_files/'),
        ),
    ]
