# Generated by Django 4.2.11 on 2025-05-11 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Arcadyan_Web", "0002_remove_uploadedlogfile_filename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("enable_idx_list", models.JSONField()),
                ("white_list", models.JSONField()),
                ("black_list", models.JSONField()),
                ("color_list", models.JSONField()),
                ("color_type_list", models.JSONField(default=list)),
                ("log_filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
