# Generated by Django 4.2.11 on 2025-05-11 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Arcadyan_Web", "0003_savedfilterconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedlogfile",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadedlogfile",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AddField(
            model_name="uploadedlogfile",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
