# Generated by Django 4.2.11 on 2025-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcadyan_Web', '0004_uploadedlogfile_progress_uploadedlogfile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilterconfig',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='savedfilterconfig',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedfilterconfig',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadedlogfile',
            name='status',
            field=models.CharField(default='Pending', max_length=1000),
        ),
    ]
